//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.22 at 09:12:09 PM CST 
//


package org.suren.autotest.platform.schemas.autotest;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="engine" type="{http://surenpi.com}engineType"/>
 *         &lt;element name="includePage" type="{http://surenpi.com}includePageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="pages">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="page" type="{http://surenpi.com}pageType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="pagePackage" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dataSources" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dataSource" type="{http://surenpi.com}dataSourceType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "engine",
    "includePage",
    "pages",
    "dataSources"
})
@XmlRootElement(name = "autotest")
public class Autotest {

    @XmlElement(required = true)
    protected EngineType engine;
    protected List<IncludePageType> includePage;
    @XmlElement(required = true)
    protected Autotest.Pages pages;
    protected Autotest.DataSources dataSources;

    /**
     * Gets the value of the engine property.
     * 
     * @return
     *     possible object is
     *     {@link EngineType }
     *     
     */
    public EngineType getEngine() {
        return engine;
    }

    /**
     * Sets the value of the engine property.
     * 
     * @param value
     *     allowed object is
     *     {@link EngineType }
     *     
     */
    public void setEngine(EngineType value) {
        this.engine = value;
    }

    /**
     * Gets the value of the includePage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includePage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludePage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncludePageType }
     * 
     * 
     */
    public List<IncludePageType> getIncludePage() {
        if (includePage == null) {
            includePage = new ArrayList<IncludePageType>();
        }
        return this.includePage;
    }

    /**
	 * @param includePage the includePage to set
	 */
	public void setIncludePage(List<IncludePageType> includePage)
	{
		this.includePage = includePage;
	}

	/**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link Autotest.Pages }
     *     
     */
    public Autotest.Pages getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Autotest.Pages }
     *     
     */
    public void setPages(Autotest.Pages value) {
        this.pages = value;
    }

    /**
     * Gets the value of the dataSources property.
     * 
     * @return
     *     possible object is
     *     {@link Autotest.DataSources }
     *     
     */
    public Autotest.DataSources getDataSources() {
        return dataSources;
    }

    /**
     * Sets the value of the dataSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link Autotest.DataSources }
     *     
     */
    public void setDataSources(Autotest.DataSources value) {
        this.dataSources = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dataSource" type="{http://surenpi.com}dataSourceType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataSource"
    })
    public static class DataSources {

        @XmlElement(required = true)
        protected List<DataSourceType> dataSource;

        /**
         * Gets the value of the dataSource property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dataSource property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDataSource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataSourceType }
         * 
         * 
         */
        public List<DataSourceType> getDataSource() {
            if (dataSource == null) {
                dataSource = new ArrayList<DataSourceType>();
            }
            return this.dataSource;
        }

		/**
		 * @param dataSource the dataSource to set
		 */
		public void setDataSource(List<DataSourceType> dataSource)
		{
			this.dataSource = dataSource;
		}

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="page" type="{http://surenpi.com}pageType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="pagePackage" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "page"
    })
    public static class Pages {

        @XmlElement(required = true)
        protected List<PageType> page;
        @XmlAttribute(name = "pagePackage")
        protected String pagePackage;

        /**
         * Gets the value of the page property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the page property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PageType }
         * 
         * 
         */
        public List<PageType> getPage() {
            if (page == null) {
                page = new ArrayList<PageType>();
            }
            return this.page;
        }

        /**
		 * @param page the page to set
		 */
		public void setPage(List<PageType> page)
		{
			this.page = page;
		}

		/**
         * Gets the value of the pagePackage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPagePackage() {
            return pagePackage;
        }

        /**
         * Sets the value of the pagePackage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPagePackage(String value) {
            this.pagePackage = value;
        }

    }

}
