//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.22 at 09:12:09 PM CST 
//


package org.suren.autotest.platform.schemas.autotest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fieldTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fieldTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="input"/>
 *     &lt;enumeration value="button"/>
 *     &lt;enumeration value="select"/>
 *     &lt;enumeration value="file_upload"/>
 *     &lt;enumeration value="check_box_group"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "fieldTypeEnum")
@XmlEnum
public enum FieldTypeEnum {


    /**
     * �ı����ı�������������ַ��Ԫ��
     * 
     */
    @XmlEnumValue("input")
    INPUT("input"),

    /**
     * ��ť����Ҫ��������������Ԫ��
     * 
     */
    @XmlEnumValue("button")
    BUTTON("button"),

    /**
     * �����б�Ԫ��
     * 
     */
    @XmlEnumValue("select")
    SELECT("select"),

    /**
     * ����˻ᴥ���ļ��ϴ��İ�ť
     * 
     */
    @XmlEnumValue("file_upload")
    FILE_UPLOAD("file_upload"),

    /**
     * �����ࣩѡ��ť�����ڵĸ���parent��Ԫ��
     * 
     */
    @XmlEnumValue("check_box_group")
    CHECK_BOX_GROUP("check_box_group");
    private final String value;

    FieldTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FieldTypeEnum fromValue(String v) {
        for (FieldTypeEnum c: FieldTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

	/**
	 * @return the value
	 */
	public String getValue()
	{
		return value;
	}

}
