//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.22 at 09:12:09 PM CST 
//


package org.suren.autotest.platform.schemas.autotest;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.suren.autotest.platform.schemas.autotest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.suren.autotest.platform.schemas.autotest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Autotest }
     * 
     */
    public Autotest createAutotest() {
        return new Autotest();
    }

    /**
     * Create an instance of {@link EngineType }
     * 
     */
    public EngineType createEngineType() {
        return new EngineType();
    }

    /**
     * Create an instance of {@link IncludePageType }
     * 
     */
    public IncludePageType createIncludePageType() {
        return new IncludePageType();
    }

    /**
     * Create an instance of {@link Autotest.Pages }
     * 
     */
    public Autotest.Pages createAutotestPages() {
        return new Autotest.Pages();
    }

    /**
     * Create an instance of {@link Autotest.DataSources }
     * 
     */
    public Autotest.DataSources createAutotestDataSources() {
        return new Autotest.DataSources();
    }

    /**
     * Create an instance of {@link PageFieldLocators }
     * 
     */
    public PageFieldLocators createPageFieldLocators() {
        return new PageFieldLocators();
    }

    /**
     * Create an instance of {@link PageType }
     * 
     */
    public PageType createPageType() {
        return new PageType();
    }

    /**
     * Create an instance of {@link PageFieldLocator }
     * 
     */
    public PageFieldLocator createPageFieldLocator() {
        return new PageFieldLocator();
    }

    /**
     * Create an instance of {@link DataSourceType }
     * 
     */
    public DataSourceType createDataSourceType() {
        return new DataSourceType();
    }

    /**
     * Create an instance of {@link PageFieldType }
     * 
     */
    public PageFieldType createPageFieldType() {
        return new PageFieldType();
    }

}
