//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.22 at 09:12:09 PM CST 
//


package org.suren.autotest.platform.schemas.autotest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pageFieldLocatorTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="pageFieldLocatorTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="byId"/>
 *     &lt;enumeration value="byCss"/>
 *     &lt;enumeration value="byName"/>
 *     &lt;enumeration value="byXpath"/>
 *     &lt;enumeration value="byLinkText"/>
 *     &lt;enumeration value="byPartialLinkText"/>
 *     &lt;enumeration value="byTagName"/>
 *     &lt;enumeration value="byIFrame"/>
 *     &lt;enumeration value="byIFrameIndex"/>
 *     &lt;enumeration value="byText"/>
 *     &lt;enumeration value="byXAttr"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "pageFieldLocatorTypeEnum")
@XmlEnum
public enum PageFieldLocatorTypeEnum {


    /**
     * ���Ԫ������idֵ��λ��ȫ��Ψһ
     * 
     */
    @XmlEnumValue("byId")
    BY_ID("byId"),

    /**
     * ���Ԫ������classֵ��λ��ͨ�����ڶ�λһ��Ԫ��
     * 
     */
    @XmlEnumValue("byCss")
    BY_CSS("byCss"),

    /**
     * ���Ԫ������nameֵ��λ��ͨ����һ���?��Ψһ
     * 
     */
    @XmlEnumValue("byName")
    BY_NAME("byName"),

    /**
     * ���Ԫ��·����xpath����λ
     * 
     */
    @XmlEnumValue("byXpath")
    BY_XPATH("byXpath"),

    /**
     * ���aԪ�ص��ı�ֵ��λ
     * 
     */
    @XmlEnumValue("byLinkText")
    BY_LINK_TEXT("byLinkText"),

    /**
     * ���aԪ�صĲ����ı�ֵ��λ
     * 
     */
    @XmlEnumValue("byPartialLinkText")
    BY_PARTIAL_LINK_TEXT("byPartialLinkText"),

    /**
     * ���Ԫ�ص���ƶ�λ��ͨ�����ڶ�λһ��Ԫ��
     * 
     */
    @XmlEnumValue("byTagName")
    BY_TAG_NAME("byTagName"),

    /**
     * ���Ԫ��iframe����ƻ���idֵ��λ
     * 
     */
    @XmlEnumValue("byIFrame")
    BY_I_FRAME("byIFrame"),

    /**
     * ���Ԫ��iframe���������λ����1��ʼ
     * 
     */
    @XmlEnumValue("byIFrameIndex")
    BY_I_FRAME_INDEX("byIFrameIndex"),
    @XmlEnumValue("byText")
    BY_TEXT("byText"),
    @XmlEnumValue("byXAttr")
    BY_X_ATTR("byXAttr");
    private final String value;

    PageFieldLocatorTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PageFieldLocatorTypeEnum fromValue(String v) {
        for (PageFieldLocatorTypeEnum c: PageFieldLocatorTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

	/**
	 * @return the value
	 */
	public String getValue()
	{
		return value;
	}

}
