//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.22 at 09:12:27 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://datasource.surenpi.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.suren.autotest.platform.schemas.datasource;
