//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.20 at 08:57:45 AM CST 
//


package org.suren.autotest.platform.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pageFieldLocatorTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="pageFieldLocatorTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="byId"/>
 *     &lt;enumeration value="byCss"/>
 *     &lt;enumeration value="byName"/>
 *     &lt;enumeration value="byXpath"/>
 *     &lt;enumeration value="byLinkText"/>
 *     &lt;enumeration value="byPartialLinkText"/>
 *     &lt;enumeration value="byTagName"/>
 *     &lt;enumeration value="byIFrame"/>
 *     &lt;enumeration value="byIFrameIndex"/>
 *     &lt;enumeration value="byText"/>
 *     &lt;enumeration value="byXAttr"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "pageFieldLocatorTypeEnum")
@XmlEnum
public enum PageFieldLocatorTypeEnum {


    /**
     * 根据元素属性id值定位，全局唯一
     * 
     */
    @XmlEnumValue("byId")
    BY_ID("byId"),

    /**
     * 根据元素属性class值定位，通常用于定位一类元素
     * 
     */
    @XmlEnumValue("byCss")
    BY_CSS("byCss"),

    /**
     * 根据元素属性name值定位，通常在一个表单中唯一
     * 
     */
    @XmlEnumValue("byName")
    BY_NAME("byName"),

    /**
     * 根据元素路径（xpath）定位
     * 
     */
    @XmlEnumValue("byXpath")
    BY_XPATH("byXpath"),

    /**
     * 根据a元素的文本值定位
     * 
     */
    @XmlEnumValue("byLinkText")
    BY_LINK_TEXT("byLinkText"),

    /**
     * 根据a元素的部分文本值定位
     * 
     */
    @XmlEnumValue("byPartialLinkText")
    BY_PARTIAL_LINK_TEXT("byPartialLinkText"),

    /**
     * 根据元素的名称定位，通常用于定位一类元素
     * 
     */
    @XmlEnumValue("byTagName")
    BY_TAG_NAME("byTagName"),

    /**
     * 根据元素iframe的名称或者id值定位
     * 
     */
    @XmlEnumValue("byIFrame")
    BY_I_FRAME("byIFrame"),

    /**
     * 根据元素iframe的序号来定位，从1开始
     * 
     */
    @XmlEnumValue("byIFrameIndex")
    BY_I_FRAME_INDEX("byIFrameIndex"),
    @XmlEnumValue("byText")
    BY_TEXT("byText"),
    @XmlEnumValue("byXAttr")
    BY_X_ATTR("byXAttr");
    private final String value;

    PageFieldLocatorTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PageFieldLocatorTypeEnum fromValue(String v) {
        for (PageFieldLocatorTypeEnum c: PageFieldLocatorTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
