//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.22 at 09:12:44 PM CST 
//


package org.suren.autotest.platform.schemas.suite;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="actionEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="fillValue"/>
 *     &lt;enumeration value="appendValue"/>
 *     &lt;enumeration value="fillNotBlankValue"/>
 *     &lt;enumeration value="click"/>
 *     &lt;enumeration value="enter"/>
 *     &lt;enumeration value="upload"/>
 *     &lt;enumeration value="randomUpload"/>
 *     &lt;enumeration value="selectByValue"/>
 *     &lt;enumeration value="selectByIndex"/>
 *     &lt;enumeration value="selectByText"/>
 *     &lt;enumeration value="select"/>
 *     &lt;enumeration value="randomSelect"/>
 *     &lt;enumeration value="checkByValue"/>
 *     &lt;enumeration value="checkByText"/>
 *     &lt;enumeration value="hover"/>
 *     &lt;enumeration value="invoke"/>
 *     &lt;enumeration value="sequence"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "actionEnum")
@XmlEnum
public enum ActionEnum {
	@XmlEnumValue("fillValue")
    FILL_VALUE("fillValue"),
    
	@XmlEnumValue("appendValue")
	APPEND_VALUE("appendValue"),
    
	@XmlEnumValue("fillNotBlankValue")
	FILL_NOT_BLANK_VALUE("fillNotBlankValue"),
    
    @XmlEnumValue("click")
    CLICK("click"),

    @XmlEnumValue("enter")
    ENTER("enter"),

    @XmlEnumValue("upload")
    UPLOAD("upload"),

    @XmlEnumValue("randomUpload")
    RANDOM_UPLOAD("randomUpload"),

    @XmlEnumValue("selectByValue")
    SELECT_BY_VALUE("selectByValue"),

    @XmlEnumValue("selectByIndex")
    SELECT_BY_INDEX("selectByIndex"),

    @XmlEnumValue("selectByText")
    SELECT_BY_TEXT("selectByText"),

    @XmlEnumValue("select")
    SELECT("select"),

    @XmlEnumValue("randomSelect")
    RANDOM_SELECT("randomSelect"),

    @XmlEnumValue("checkByValue")
    CHECK_BY_VALUE("checkByValue"),

    @XmlEnumValue("checkByText")
    CHECK_BY_TEXT("checkByText"),

    @XmlEnumValue("hover")
    HOVER("hover"),

    @XmlEnumValue("invoke")
    INVOKE("invoke"),

    @XmlEnumValue("sequence")
    SEQUENCE("sequence");
	
    private final String value;

    ActionEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionEnum fromValue(String v) {
        for (ActionEnum c: ActionEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

	/**
	 * @return the value
	 */
	public String getValue()
	{
		return value;
	}

}
