//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.22 at 09:12:44 PM CST 
//


package org.suren.autotest.platform.schemas.suite;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for errorLinesEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="errorLinesEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="stop"/>
 *     &lt;enumeration value="continue"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "errorLinesEnum")
@XmlEnum
public enum ErrorLinesEnum {


    /**
     * 
     * 						当使用当前数据组运行报错时停止程序。
     * 					
     * 
     */
    @XmlEnumValue("stop")
    STOP("stop"),

    /**
     * 
     * 						当使用当前数据组运行报错时忽略并继续程序。
     * 					
     * 
     */
    @XmlEnumValue("continue")
    CONTINUE("continue");
    private final String value;

    ErrorLinesEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ErrorLinesEnum fromValue(String v) {
        for (ErrorLinesEnum c: ErrorLinesEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
