//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.20 at 08:57:45 AM CST 
//


package org.suren.autotest.platform.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataSourceTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="dataSourceTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="xml_data_source"/>
 *     &lt;enumeration value="excel_data_source"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "dataSourceTypeEnum")
@XmlEnum
public enum DataSourceTypeEnum {


    /**
     * XML格式的数据源
     * 
     */
    @XmlEnumValue("xml_data_source")
    XML_DATA_SOURCE("xml_data_source"),
    @XmlEnumValue("excel_data_source")
    EXCEL_DATA_SOURCE("excel_data_source");
    private final String value;

    DataSourceTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataSourceTypeEnum fromValue(String v) {
        for (DataSourceTypeEnum c: DataSourceTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
